//! Turning rustdoc text into Markdown that Docusaurus (MDX) reads as written.

/// The line every generated file carries near its top.
pub const MARKER: &str = "generated by canon-docs, do not edit";

/// The front matter every generated page starts with; its first line is the marker.
pub fn front_matter(title: &str, sidebar_label: &str, description: &str) -> String {
    format!(
        "---\n# {MARKER}\ntitle: {}\nsidebar_label: {}\ndescription: {}\n---\n\n",
        quoted(title),
        quoted(sidebar_label),
        quoted(description)
    )
}

fn quoted(text: &str) -> String {
    format!("\"{}\"", text.replace('\\', "\\\\").replace('"', "\\\""))
}

/// Inside an inline code span: the length of the backtick run that opened it.
type CodeSpan = Option<usize>;

/// Converts rustdoc prose to MDX: drops the brackets of intra-doc links (`` [`Ir`] `` becomes
/// `` `Ir` ``) while keeping Markdown links, and, when `escape` is set, escapes what MDX would read
/// as JSX or an expression. Inline code is left untouched, including a span that continues from an
/// earlier line of the same paragraph, which `span` carries.
fn convert(line: &str, span: &mut CodeSpan, escape: bool) -> String {
    let chars: Vec<char> = line.chars().collect();
    let mut out = String::with_capacity(line.len());
    let mut i = 0;
    while i < chars.len() {
        let c = chars[i];
        if c == '`' {
            let run = chars[i..].iter().take_while(|&&d| d == '`').count();
            match *span {
                None => *span = Some(run),
                Some(open) if open == run => *span = None,
                Some(_) => {}
            }
            out.extend(std::iter::repeat_n('`', run));
            i += run;
            continue;
        }
        if span.is_none() {
            if c == '['
                && let Some(close) = chars[i + 1..].iter().position(|&d| d == ']')
            {
                let close = i + 1 + close;
                let inner: String = chars[i + 1..close].iter().collect();
                let next = chars.get(close + 1).copied();
                if next != Some('(')
                    && next != Some('[')
                    && !inner.is_empty()
                    && inner.matches('`').count().is_multiple_of(2)
                {
                    out.push_str(&convert(&inner, &mut None, escape));
                    i = close + 1;
                    continue;
                }
            }
            if escape {
                match c {
                    '{' => out.push_str("\\{"),
                    '}' => out.push_str("\\}"),
                    '<' => out.push_str("&lt;"),
                    '>' => out.push_str("&gt;"),
                    _ => out.push(c),
                }
                i += 1;
                continue;
            }
        }
        out.push(c);
        i += 1;
    }
    out
}

/// One line of rustdoc prose as MDX.
pub fn prose(line: &str) -> String {
    convert(line, &mut None, true)
}

/// A doc comment as one line of plain text, intra-doc links unwrapped and nothing escaped.
pub fn plain(doc: &str) -> String {
    let joined = doc
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    convert(&joined, &mut None, false)
}

/// A doc comment as one table cell: one line, MDX-safe, pipes escaped.
pub fn cell(doc: &str) -> String {
    let joined = doc
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join(" ");
    prose(&joined).replace('|', "\\|")
}

/// A multi-line doc comment as MDX: fenced code is kept as written, prose is escaped, and every
/// heading moves `shift` levels down so it nests under the page's own headings.
pub fn block(doc: &str, shift: usize) -> String {
    let mut out = String::new();
    let mut in_fence = false;
    let mut span = None;
    for line in doc.lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with("```") {
            in_fence = !in_fence;
            span = None;
            out.push_str(line);
        } else if in_fence {
            out.push_str(line);
        } else if trimmed.is_empty() {
            span = None;
        } else if trimmed.starts_with('#') {
            out.push_str(&"#".repeat(shift));
            out.push_str(&convert(line, &mut span, true));
        } else {
            out.push_str(&convert(line, &mut span, true));
        }
        out.push('\n');
    }
    out
}

/// A Markdown table.
pub fn table(header: &[&str], rows: &[Vec<String>]) -> String {
    let mut out = format!("| {} |\n", header.join(" | "));
    out.push_str(&format!(
        "|{}\n",
        header.iter().map(|_| "---|").collect::<String>()
    ));
    for row in rows {
        out.push_str(&format!("| {} |\n", row.join(" | ")));
    }
    out
}

/// Inline code, safe inside a table cell.
pub fn code(text: &str) -> String {
    format!("`{}`", text.replace('|', "\\|"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn intra_doc_links_lose_their_brackets_and_markdown_links_stay() {
        assert_eq!(
            prose("see [`Ir::canonical_json`] and [ELS](https://x)"),
            "see `Ir::canonical_json` and [ELS](https://x)"
        );
    }

    #[test]
    fn code_is_left_alone_and_prose_is_escaped() {
        assert_eq!(
            prose("`{\"all\": []}` is {true} for <n>"),
            "`{\"all\": []}` is \\{true\\} for &lt;n&gt;"
        );
    }

    #[test]
    fn code_spans_continue_across_lines_and_double_backticks_hold_single_ones() {
        assert_eq!(
            block("a `<what\ndiffered>` b <c>\n\n`` `x` `` {y}", 0),
            "a `<what\ndiffered>` b &lt;c&gt;\n\n`` `x` `` \\{y\\}\n"
        );
    }

    #[test]
    fn cells_are_one_line_with_pipes_escaped() {
        assert_eq!(cell("a\n b | c"), "a b \\| c");
    }

    #[test]
    fn fences_are_kept_and_headings_shifted() {
        let doc = "# Title\n```yaml\nkey: {a: 1}\n```\ntext {x}";
        assert_eq!(
            block(doc, 1),
            "## Title\n```yaml\nkey: {a: 1}\n```\ntext \\{x\\}\n"
        );
    }
}
