//! The `b10x-status/1` document the landing page's status strip and the status page's table both
//! render. The capabilities, their wording and their links are hand-written in
//! `website/status.yaml`; each names the AEP story that delivers it, and its status is read from
//! that story, never typed: an implemented story is shipped, one that is not but cites an Atlas ADR
//! is decided, and any other is planned.

use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

use serde::Deserialize;

use crate::json::{self, Json, obj};

pub const SOURCE: &str = "website/status.yaml";
pub const FILE: &str = "status.json";
const STORIES: &str = ".engineering/planning/story";

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Source {
    items: Vec<Item>,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Item {
    label: String,
    area: String,
    story: String,
    detail: String,
    #[serde(default)]
    href: Option<String>,
}

/// The front matter of an AEP story, as far as the status needs it.
#[derive(Deserialize)]
struct Story {
    status: String,
    #[serde(default)]
    refs: Vec<Ref>,
}

#[derive(Deserialize)]
struct Ref {
    provider: String,
    reference: String,
}

/// The status a story gives the capability it delivers.
fn status_of(story: &Story) -> &'static str {
    if story.status == "implemented" {
        "shipped"
    } else if story
        .refs
        .iter()
        .any(|r| r.provider == "atlas" && r.reference.starts_with("adr:"))
    {
        "decided"
    } else {
        "planned"
    }
}

/// The YAML front matter of a planning Markdown file.
fn front_matter<'a>(text: &'a str, path: &str) -> Result<&'a str, String> {
    let rest = text
        .strip_prefix("---\n")
        .ok_or_else(|| format!("{path}: no front matter"))?;
    let end = rest
        .find("\n---\n")
        .ok_or_else(|| format!("{path}: unterminated front matter"))?;
    Ok(&rest[..end + 1])
}

fn read_story(root: &Path, id: &str) -> Result<Story, String> {
    let name = id
        .strip_prefix("story:")
        .filter(|name| {
            !name.is_empty()
                && name
                    .bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
        })
        .ok_or_else(|| format!("{SOURCE}: {id:?} is not a story id"))?;
    let path = format!("{STORIES}/{name}.md");
    let text = fs::read_to_string(root.join(&path))
        .map_err(|error| format!("{SOURCE}: {id} has no story at {path}: {error}"))?;
    serde_yaml_ng::from_str(front_matter(&text, &path)?).map_err(|error| format!("{path}: {error}"))
}

/// The status document from the source file and the stories it names.
fn document(source: &str, story: impl Fn(&str) -> Result<Story, String>) -> Result<String, String> {
    let parsed: Source =
        serde_yaml_ng::from_str(source).map_err(|error| format!("{SOURCE}: {error}"))?;
    let mut labels = BTreeSet::new();
    let mut items = Vec::new();
    for item in parsed.items {
        if !labels.insert(item.label.clone()) {
            return Err(format!("{SOURCE}: {:?} is listed twice", item.label));
        }
        for (key, value) in [
            ("label", &item.label),
            ("area", &item.area),
            ("detail", &item.detail),
        ] {
            if value.trim().is_empty() {
                return Err(format!("{SOURCE}: {:?} has an empty {key}", item.label));
            }
        }
        let status = status_of(&story(&item.story)?);
        let mut members = vec![
            ("label".to_owned(), json::str(item.label)),
            ("status".to_owned(), json::str(status)),
            ("detail".to_owned(), json::str(item.detail)),
        ];
        if let Some(href) = item.href {
            members.push(("href".to_owned(), json::str(href)));
        }
        members.push(("area".to_owned(), json::str(item.area)));
        items.push(Json::Obj(members));
    }
    if items.is_empty() {
        return Err(format!("{SOURCE}: no items"));
    }
    Ok(obj([
        ("format", json::str("b10x-status/1")),
        (
            "source",
            json::str(
                "Generated by canon-docs from website/status.yaml; each status is read from the AEP story it names",
            ),
        ),
        ("items", Json::Arr(items)),
    ])
    .pretty())
}

/// The status document of the repository at `root`.
pub fn generate(root: &Path) -> Result<String, String> {
    let source = fs::read_to_string(root.join(SOURCE))
        .map_err(|error| format!("reading {SOURCE}: {error}"))?;
    document(&source, |id| read_story(root, id))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn story(status: &str, adr: bool) -> Story {
        Story {
            status: status.to_owned(),
            refs: adr
                .then(|| Ref {
                    provider: "atlas".to_owned(),
                    reference: "adr:0081".to_owned(),
                })
                .into_iter()
                .collect(),
        }
    }

    #[test]
    fn a_status_is_read_from_the_story_never_typed() {
        assert_eq!(status_of(&story("implemented", true)), "shipped");
        assert_eq!(status_of(&story("implemented", false)), "shipped");
        assert_eq!(status_of(&story("draft", true)), "decided");
        assert_eq!(status_of(&story("proposed", false)), "planned");
        let other = Story {
            status: "draft".to_owned(),
            refs: vec![Ref {
                provider: "taskboard".to_owned(),
                reference: "adr:1".to_owned(),
            }],
        };
        assert_eq!(status_of(&other), "planned");
    }

    #[test]
    fn the_document_keeps_source_order_and_refuses_a_typed_status() {
        let source = "items:\n  - label: B\n    area: X\n    story: story:b\n    detail: d\n    href: /docs/b\n  - label: A\n    area: Y\n    story: story:a\n    detail: e\n";
        let doc = document(source, |id| {
            Ok(story(
                if id == "story:b" {
                    "implemented"
                } else {
                    "draft"
                },
                false,
            ))
        })
        .expect("generates");
        assert!(doc.starts_with("{\n  \"format\": \"b10x-status/1\",\n"));
        let b = doc.find("\"label\": \"B\"").unwrap();
        let a = doc.find("\"label\": \"A\"").unwrap();
        assert!(b < a);
        assert!(doc.contains("\"status\": \"shipped\""));
        assert!(doc.contains("\"status\": \"planned\""));

        let typed = "items:\n  - label: A\n    area: Y\n    story: story:a\n    detail: e\n    status: shipped\n";
        assert!(document(typed, |_| Ok(story("draft", false))).is_err());
        let twice = "items:\n  - {label: A, area: Y, story: story:a, detail: e}\n  - {label: A, area: Y, story: story:a, detail: e}\n";
        assert!(
            document(twice, |_| Ok(story("draft", false)))
                .unwrap_err()
                .contains("twice")
        );
    }

    #[test]
    fn every_item_names_a_story_of_this_repository() {
        let root = std::path::PathBuf::from(
            std::env::var_os("CARGO_MANIFEST_DIR").expect("run this test through cargo"),
        )
        .join("../..");
        generate(&root).expect("website/status.yaml resolves against the planning store");
        assert!(read_story(&root, "story:../x").is_err());
        assert!(read_story(&root, "story:no-such-story").is_err());
    }
}
