import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {withProductSite} from '@beyond10x/docs-system/product-site';

// The landing page is `product.json`, rendered by the shared docs-system product-site template.
// Hand-written pages (concepts, guides, status) live in `docs/`. Everything under
// `docs/reference/`, `static/schemas/` and `data/` is generated by `canon-docs generate` from the
// repository itself and checked for drift by `task check`; edit the source, not those files.

const config: Config = {
  title: 'Canon',
  tagline: 'A formal language and deterministic calculus for evidence-governed protocols.',
  favicon: 'img/mark.svg',

  future: {v4: true},
  url: 'https://beyond10x.github.io',
  baseUrl: '/canon/',
  organizationName: 'beyond10x',
  projectName: 'canon',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  markdown: {
    hooks: {onBrokenMarkdownLinks: 'throw'},
  },
  plugins: [
    [
      '@docusaurus/plugin-client-redirects',
      {
        // The documentation lived at the site root until the landing page took it; every old
        // address still lands on its page.
        createRedirects(existingPath: string) {
          const match = existingPath.match(/^\/docs(\/.+)$/);
          return match ? [match[1]] : undefined;
        },
      },
    ],
  ],
  i18n: {defaultLocale: 'en', locales: ['en']},

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: 'docs',
          editUrl: 'https://github.com/beyond10x/canon/tree/main/website/',
        },
        blog: false,
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    navbar: {
      title: 'Canon',
      items: [
        {to: '/docs/', label: 'Docs', position: 'left', activeBaseRegex: '^/canon/docs/(?!reference/investigation-example|status/)'},
        {to: '/docs/reference/investigation-example', label: 'Example', position: 'left'},
        {to: '/docs/reference/cli', label: 'CLI', position: 'left'},
        {to: '/docs/status/where-this-stands', label: 'Status', position: 'left'},
        {href: 'https://github.com/beyond10x/canon', label: 'GitHub', position: 'right'},
      ],
    },
    footer: {
      links: [
        {
          title: 'Documentation',
          items: [
            {label: 'What Canon is', to: '/docs/'},
            {label: 'Getting started', to: '/docs/getting-started'},
            {label: 'The protocol/1 language', to: '/docs/concepts/protocols'},
            {label: 'protocol/1 reference', to: '/docs/reference/protocol'},
            {label: 'CLI reference', to: '/docs/reference/cli'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Status and roadmap', to: '/docs/status/where-this-stands'},
            {label: 'Source', href: 'https://github.com/beyond10x/canon'},
          ],
        },
        {
          title: 'Family',
          items: [
            {label: 'ELS', href: 'https://beyond10x.github.io/els/'},
            {label: 'Loom', href: 'https://beyond10x.github.io/loom/'},
            {label: 'ESS', href: 'https://beyond10x.github.io/ess/'},
          ],
        },
      ],
      copyright: 'A beyond10x project · Apache-2.0 · built with Docusaurus and the docs-system product template.',
    },
  } satisfies Preset.ThemeConfig,
};

export default withProductSite(config, {landing: './product.json', product: 'canon'});
