import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import {themes as prismThemes} from 'prism-react-renderer';
import docsSystemPlugin, {ecosystemFooterGroup, ecosystemNavbarItems} from '@beyond10x/docs-system/docusaurus';

// Hand-written pages (concepts, guides, status) live in `docs/`. Everything under
// `docs/reference/` and `static/schemas/` is generated by `canon-docs generate` from the
// repository itself and checked for drift by `task check`; edit the source, not those files.

const config: Config = {
  title: 'Canon',
  tagline:
    'A formal language and deterministic calculus for evidence-governed protocols.',
  favicon: 'img/mark.svg',

  future: {v4: true},
  url: 'https://beyond10x.github.io',
  baseUrl: '/canon/',
  organizationName: 'beyond10x',
  projectName: 'canon',
  deploymentBranch: 'gh-pages',
  trailingSlash: false,
  onBrokenLinks: 'throw',

  markdown: {
    hooks: {onBrokenMarkdownLinks: 'throw'},
  },
  plugins: [docsSystemPlugin],
  i18n: {defaultLocale: 'en', locales: ['en']},

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
          editUrl: 'https://github.com/beyond10x/canon/tree/main/website/',
        },
        blog: false,
        theme: {customCss: './src/css/custom.css'},
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {respectPrefersColorScheme: true},
    navbar: {
      title: 'Canon',
      logo: {alt: 'Canon', src: 'img/mark.svg', width: 26, height: 26},
      items: [
        ...ecosystemNavbarItems(),
        {type: 'docSidebar', sidebarId: 'docsSidebar', position: 'left', label: 'Documentation'},
        {to: '/reference/investigation-example', label: 'Example', position: 'left'},
        {to: '/status/where-this-stands', label: 'Status', position: 'left'},
        {
          href: 'https://github.com/beyond10x/canon',
          label: 'GitHub',
          position: 'right',
          className: 'navbar-github-link',
          'aria-label': 'GitHub repository',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        ecosystemFooterGroup(),
        {
          title: 'Documentation',
          items: [
            {label: 'What Canon is', to: '/'},
            {label: 'Getting started', to: '/getting-started'},
            {label: 'The protocol/1 language', to: '/concepts/protocols'},
            {label: 'protocol/1 reference', to: '/reference/protocol'},
            {label: 'CLI reference', to: '/reference/cli'},
          ],
        },
        {
          title: 'Project',
          items: [
            {label: 'Status and roadmap', to: '/status/where-this-stands'},
            {label: 'Source', href: 'https://github.com/beyond10x/canon'},
            {label: 'ELS, the engineering domain', href: 'https://github.com/beyond10x/els'},
          ],
        },
      ],
      logo: {alt: 'Canon', src: 'img/mark.svg', href: '/', width: 22, height: 22},
      copyright:
        '<span class="footer__claim">What is known, what is owed, and what has been earned.</span>' +
        'Canon · Apache-2.0 · built with Docusaurus.',
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'yaml', 'json', 'bash'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
